language: python

env:
  global:
    # Variables just to silence pcaspy setup.
    - EPICS_BASE=~
    - EPICS_HOST_ARCH=linux-x86_64
    - OFFICIAL_REPO="slaclab/pydm"
    - secure: "g7JqJMMB4LL0bM0h1rUN8bR2/CWt+jHLW+nknroyU6+kZc2oi6WLw7FSapCV23nJkyzoBZrvHokKBz/hml/lhp4wBuxWfm4E9h8qdyZgkA7OzWkJ2SxNvChi3mASLfvavkuIS/yCDxdhlcQsSNr3kdwkTRQuuKPqWuLzYLFHesCYOtWtRTn/9bzEPsvLp5/3ul+PY8ZsAdcdUEEJPgeW8P+JS960Jf4JsQ2QEl3ZOS3+l4SF7Z72yr0exmrWp8dt2rVuPXDLVHVos08Wx1tTL5Xwp8v33sAt9SHR40li+Q5KNHyA6ZC6Jgz7ZeDyxu39V7QvA55sF5+1J9UG0SrStmChbJ5lTeOx9wgxq6Ha8hrcsTaMPuk5eKcLvfZliSZ4lXxlSf8R/+HFrZNnS9DvrulWY/MVI4AdrON9RF9RDPGtfMyit8CKYOKp9XzKPDHeGFGZCfE9F0isLK/2YqIem63FwB1uFew6cFyRHIM1Ygtb7dzm/AE+dJhkY4iwR8jVnQF9qy7DwAAjbRohL40KvjcrZmn5rxH/VpPjxbifArEhtymYMgTGPfSgQAJO17yOcJdNKODZ/40qghlh0dv1loMxGPM73S9VLdsHqDQaaIptpQi2Z/y7pGVoiMPbZueQcSIkC04YKwJzKB1iCs2OQJ0g+kUdV4fFweMnUwa4umU="

matrix:
  include:
    - python: 2.7
      env: PYQT_VERSION=5
    - python: 3.5
      env: PYQT_VERSION=5
    - python: 3.6
      env: PYQT_VERSION=5 BUILD_DOCS=1

before_install:
  # Make sure we have the tags no matter how far from them we are.
  - git pull --unshallow
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes
  - conda install conda-build anaconda-client
  - conda update -q conda conda-build
  # Useful for debugging any issues with conda
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pyqt=$PYQT_VERSION pip numpy scipy six psutil pyqtgraph -c conda-forge
  - source activate test-environment
  - pip install requests pyepics coverage codecov coveralls pytest pytest-cov versioneer

install:
  # Debug information
  - git describe --tags --dirty --always
  - python setup.py version
  # Do the proper install
  - python setup.py install

script:
  - py.test -sv --cov=pydm --cov-report term-missing
  - set -e
  #Build docs
  - |
    if [[ -n "$DOCTR_DEPLOY_ENCRYPTION_KEY" && $BUILD_DOCS ]]; then
      pip install -r docs-requirements.txt
      pushd docs
      make html
      popd
      #Publish docs.
      doctr deploy . --built-docs docs/build/html --deploy-branch-name gh-pages
    fi

after_success:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' && $CONDA_UPLOAD_TOKEN_TAG != '' ]]; then
      conda build . -c defaults -c conda-forge -c gsecars --token $CONDA_UPLOAD_TOKEN_TAG --python $TRAVIS_PYTHON_VERSION
    fi
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == $OFFICIAL_REPO && $TRAVIS_BRANCH == 'master' && $TRAVIS_TAG == '' && $CONDA_UPLOAD_TOKEN_DEV != '' ]]; then
      conda build . -c defaults -c conda-forge -c gsecars --token $CONDA_UPLOAD_TOKEN_DEV --python $TRAVIS_PYTHON_VERSION
    fi
